### ISSUE TITLE
Bugs on 0.16.2

### ISSUE THREAD

**Issue by trafficfan** [mlverse/torch#1372]
```
> library(torch)
Torch libraries are installed but loading them was unsuccessful.
Torch libraries are installed but loading them was unsuccessful.
```
All required libs are installed, no bugs occur using 0.16.1
```
> sessionInfo()
R version 4.5.1 (2025-06-13 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26200)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] torch_0.16.2

loaded via a namespace (and not attached):
 [1] processx_3.8.6    bit_4.6.0         compiler_4.5.1    magrittr_2.0.4    cli_3.6.5        
 [6] tools_4.5.1       rstudioapi_0.17.1 Rcpp_1.1.0        bit64_4.6.0-1     xml2_1.4.1       
[11] coro_1.1.0        callr_3.7.6       ps_1.9.1          commonmark_2.0.0  rlang_1.1.6   
```

**Comment by dfalbel** [comment]
Addressed in https://github.com/mlverse/torch/pull/1373

Will prepare a new submission

**Comment by opasche** [comment]
Hi @dfalbel,

I'm submitting an update of [EQRN](https://github.com/opasche/EQRN) to CRAN, that depends on torch.
Even after specifying "torch (>= 0.16.3)" in the "Imports", for which the issue should be fixed, I still get this same startup message from torch, that [raises a Note](https://win-builder.r-project.org/incoming_pretest/EQRN_0.1.2_20251113_170656/Windows/00check.log) and prevents my update from being accepted.

    * checking whether startup messages can be suppressed ... NOTE
    Torch libraries are installed but loading them was unsuccessful.
    
    It looks like this package (or a package it requires) has a startup
    message which cannot be suppressed: see ?packageStartupMessage.

This only happens with the CRAN windows checks; with CRAN's Debian it seems to work fine. Neither does it happen locally or on GitHub servers when I run the "`R CMD check --as-cran`". 

Do you maybe have an idea on what could cause that, or on how to fix it? 
(Maybe the CRAN servers having the updated version of the torch package, but an outdated version of the LibTorch and LibLantern backend libraries?)
